- name: K8s CLI Tools Installation
  hosts: localhost
  become: true
  gather_facts: true

  vars_files:
    - defaults/main.yaml

  tasks:
    - name: Run the kubernetes cli tools installation workflow
      ansible.builtin.include_tasks: "tasks/main.yaml"
