- name: Download CLI tool archives
  block:
    - name: Download Helm archive
      ansible.builtin.get_url:
        url: "{{ helm_url }}"
        dest: "{{ temporary_folder }}/helm.tar.gz"
        mode: "0644"
        force: false
        validate_certs: true
        timeout: 60

    - name: Download kubens archive
      ansible.builtin.get_url:
        url: "{{ kubens_url }}"
        dest: "{{ temporary_folder }}/kubens.tar.gz"
        mode: "0644"
        force: false
        validate_certs: true
        timeout: 60

    - name: Download kubectx archive
      ansible.builtin.get_url:
        url: "{{ kubectx_url }}"
        dest: "{{ temporary_folder }}/kubectx.tar.gz"
        mode: "0644"
        force: false
        validate_certs: true
        timeout: 60

    - name: Download stern archive
      ansible.builtin.get_url:
        url: "{{ stern_url }}"
        dest: "{{ temporary_folder }}/stern.tar.gz"
        mode: "0644"
        force: false
        validate_certs: true
        timeout: 60
