- name: Extract CLI tool archives
  block:
    - name: Create Helm extraction directory
      ansible.builtin.file:
        path: "{{ temporary_folder }}/helm"
        state: directory
        mode: "0755"

    - name: Extract kubectx archive
      ansible.builtin.unarchive:
        src: "{{ temporary_folder }}/kubectx.tar.gz"
        dest: "{{ temporary_folder }}/"
        remote_src: true
        mode: "0755"

    - name: Extract kubens archive
      ansible.builtin.unarchive:
        src: "{{ temporary_folder }}/kubens.tar.gz"
        dest: "{{ temporary_folder }}/"
        remote_src: true
        mode: "0755"

    - name: Extract Helm archive
      ansible.builtin.unarchive:
        src: "{{ temporary_folder }}/helm.tar.gz"
        dest: "{{ temporary_folder }}/helm"
        remote_src: true
        mode: "0755"

    - name: Create stern extraction directory
      ansible.builtin.file:
        path: "{{ temporary_folder }}/stern"
        state: directory
        mode: "0755"

    - name: Extract stern archive
      ansible.builtin.unarchive:
        src: "{{ temporary_folder }}/stern.tar.gz"
        dest: "{{ temporary_folder }}/stern"
        remote_src: true
        mode: "0755"
