- name: Display installation start message
  ansible.builtin.debug:
    msg:
      - "=================================================="
      - "Starting kubernetes cli tools installation..."
      - "=================================================="

- name: Prepare temporary directory
  ansible.builtin.include_tasks: 1-setup_temporary_folder.yaml

- name: Download CLI tool archives
  ansible.builtin.include_tasks: 2-download_files.yaml

- name: Extract CLI tool archives
  ansible.builtin.include_tasks: 3-extract_files.yaml

- name: Copy CLI tool binaries to install path
  ansible.builtin.include_tasks: 4-copy_files.yaml

- name: Include post-installation tasks
  ansible.builtin.include_tasks: 5-post_install.yaml

- name: Remove temporary directory
  ansible.builtin.include_tasks: 6-cleanup.yaml


- name: Display installation completion message
  ansible.builtin.debug:
    msg:
      - "=================================================="
      - "kubernetes cli tools installation completed successfully."
      - "=================================================="
