- name: Copy helm Binaries to Install Path
  ansible.builtin.copy:
    src: "{{ temporary_folder }}/helm/linux-amd64/helm"
    dest: "{{ install_path }}"
    mode: "0550"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    remote_src: true

- name: Copy kubectx Binaries to Install Path
  ansible.builtin.copy:
    src: "{{ temporary_folder }}/kubectx"
    dest: "{{ install_path }}"
    mode: "0550"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    remote_src: true

- name: Copy kubens Binaries to Install Path
  ansible.builtin.copy:
    src: "{{ temporary_folder }}/kubens"
    dest: "{{ install_path }}"
    mode: "0550"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    remote_src: true

- name: Copy kubens Binaries to Install Path
  ansible.builtin.copy:
    src: "{{ temporary_folder }}/stern/stern"
    dest: "{{ install_path }}"
    mode: "0550"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    remote_src: true
