- name: Copy helm Binaries to Install Path
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ install_path }}"
    mode: "0550"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    remote_src: true
  with_fileglob:
    - "{{ temporary_folder }}/helm/bin/*"
