- name: "Extract: CLI Tool Archives"
  block:
    - name: "Extract: Create helm Extraction Directory"
      ansible.builtin.file:
        path: "{{ temporary_folder }}/helm"
        state: directory
        mode: "0755"

    - name: "Extract: Unarchive helm Tarball"
      ansible.builtin.unarchive:
        src: "{{ temporary_folder }}/helm.tar.gz"
        dest: "{{ temporary_folder }}/helm"
        remote_src: true
        mode: "0755"

    - name: "Extract: Create stern Extraction Directory"
      ansible.builtin.file:
        path: "{{ temporary_folder }}/stern"
        state: directory
        mode: "0755"

    - name: "Extract: Unarchive stern Tarball"
      ansible.builtin.unarchive:
        src: "{{ temporary_folder }}/stern.tar.gz"
        dest: "{{ temporary_folder }}/stern"
        remote_src: true
        mode: "0755"
