- name: "Setup: Create Temporary Directory"
  ansible.builtin.file:
    path: "{{ temporary_folder }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
